#!/usr/bin/env python3
"""
Aggregate CSV files generated by the VBA option download process.

This script:
- Reads all CSV files matching a pattern (default: *_batch*.csv)
- Aggregates them into a single file
- Allows overriding specific fields
- Removes duplicates based on key columns
- Outputs the combined result

Usage:
    python aggregate_files.py --input-dir . --output combined.csv
    python aggregate_files.py --pattern "1EW_*.csv" --override "ccy_pair=EUR/USD"
    python aggregate_files.py --override-file overrides.json
"""

import argparse
import glob
import json
import os
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd


# CSV columns as defined in VBA SetupStagingSheet
CSV_COLUMNS = [
    "Spot_Date",
    "Premium",
    "Ticker",
    "Maturity",
    "Interest_rate",
    "Spot",
    "Strike",
    "Type",
    "Implied_Volatility",
    "Delta",
    "Vega",
    "Gamma",
    "Theta",
    "Rho",
    "Lot_size",
    "Name",
    "Reference",
    "ccy_pair",
    "Dividend",
    "DDELTA/DVOL",
    "DDELTA/DVOLDVOL",
    "DDELTA/DTIME",
    "DGAMMA/DSPOT",
    "DGAMMA/DVOL",
    "DVEGA/DVOL",
    "DVEGA/DVOLDVOL",
    "RIC",
]

# Key columns for duplicate detection
KEY_COLUMNS = ["Spot_Date", "Ticker", "Maturity", "Strike", "Type"]


def parse_override(override_str: str) -> tuple[str, str]:
    """Parse a single override string like 'column=value'."""
    if "=" not in override_str:
        raise ValueError(f"Invalid override format: {override_str}. Expected 'column=value'")
    col, val = override_str.split("=", 1)
    return col.strip(), val.strip()


def load_overrides_from_file(filepath: str) -> dict:
    """Load overrides from a JSON file."""
    with open(filepath, "r") as f:
        return json.load(f)


def find_csv_files(input_dir: str, pattern: str) -> list[str]:
    """Find all CSV files matching the pattern in the input directory."""
    search_path = os.path.join(input_dir, pattern)
    files = glob.glob(search_path)
    # Sort by modification time (oldest first)
    files.sort(key=os.path.getmtime)
    return files


def read_csv_file(filepath: str) -> pd.DataFrame:
    """Read a single CSV file with proper handling."""
    try:
        df = pd.read_csv(filepath, dtype=str)  # Read all as string initially
        print(f"  Read {len(df)} rows from {os.path.basename(filepath)}")
        return df
    except Exception as e:
        print(f"  Warning: Could not read {filepath}: {e}")
        return pd.DataFrame()


def aggregate_files(files: list[str]) -> pd.DataFrame:
    """Read and concatenate all CSV files."""
    if not files:
        return pd.DataFrame()

    print(f"\nReading {len(files)} files...")
    dfs = []
    for f in files:
        df = read_csv_file(f)
        if not df.empty:
            # Add source file column for traceability
            df["_source_file"] = os.path.basename(f)
            dfs.append(df)

    if not dfs:
        return pd.DataFrame()

    combined = pd.concat(dfs, ignore_index=True)
    print(f"\nTotal rows before deduplication: {len(combined)}")
    return combined


def apply_overrides(df: pd.DataFrame, overrides: dict) -> pd.DataFrame:
    """Apply field overrides to the dataframe."""
    if not overrides:
        return df

    print(f"\nApplying {len(overrides)} override(s)...")
    for col, value in overrides.items():
        if col in df.columns:
            print(f"  Setting {col} = {value}")
            df[col] = value
        else:
            print(f"  Warning: Column '{col}' not found in data, adding it")
            df[col] = value

    return df


def remove_duplicates(df: pd.DataFrame, keep: str = "last") -> pd.DataFrame:
    """Remove duplicate rows based on key columns."""
    # Check which key columns exist
    existing_keys = [k for k in KEY_COLUMNS if k in df.columns]

    if not existing_keys:
        print("Warning: No key columns found for deduplication")
        return df

    before_count = len(df)
    df = df.drop_duplicates(subset=existing_keys, keep=keep)
    after_count = len(df)

    if before_count != after_count:
        print(f"Removed {before_count - after_count} duplicate rows (kept {keep})")

    return df


def convert_types(df: pd.DataFrame) -> pd.DataFrame:
    """Convert columns to appropriate types."""
    # Numeric columns
    numeric_cols = [
        "Premium", "Interest_rate", "Spot", "Strike",
        "Implied_Volatility", "Delta", "Vega", "Gamma", "Theta", "Rho",
        "Lot_size", "Dividend",
        "DDELTA/DVOL", "DDELTA/DVOLDVOL", "DDELTA/DTIME",
        "DGAMMA/DSPOT", "DGAMMA/DVOL", "DVEGA/DVOL", "DVEGA/DVOLDVOL"
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Date columns
    date_cols = ["Spot_Date", "Maturity"]
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    return df


def filter_data(df: pd.DataFrame, filters: dict) -> pd.DataFrame:
    """Apply filters to the data."""
    if not filters:
        return df

    print(f"\nApplying {len(filters)} filter(s)...")
    for col, condition in filters.items():
        if col not in df.columns:
            print(f"  Warning: Filter column '{col}' not found")
            continue

        # Parse condition (e.g., ">0", "==CALL", "!=0")
        if condition.startswith(">="):
            val = float(condition[2:])
            df = df[df[col] >= val]
        elif condition.startswith("<="):
            val = float(condition[2:])
            df = df[df[col] <= val]
        elif condition.startswith(">"):
            val = float(condition[1:])
            df = df[df[col] > val]
        elif condition.startswith("<"):
            val = float(condition[1:])
            df = df[df[col] < val]
        elif condition.startswith("!="):
            val = condition[2:]
            df = df[df[col].astype(str) != val]
        elif condition.startswith("=="):
            val = condition[2:]
            df = df[df[col].astype(str) == val]
        else:
            # Default: equality check
            df = df[df[col].astype(str) == condition]

        print(f"  Filter {col} {condition}: {len(df)} rows remaining")

    return df


def main():
    parser = argparse.ArgumentParser(
        description="Aggregate CSV files from VBA option download process",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Aggregate all batch files in current directory
  python aggregate_files.py

  # Specify input directory and output file
  python aggregate_files.py --input-dir ../data --output combined.csv

  # Use custom pattern
  python aggregate_files.py --pattern "1EW_202512*.csv"

  # Override specific fields
  python aggregate_files.py --override "ccy_pair=EUR/USD" --override "Lot_size=100"

  # Load overrides from JSON file
  python aggregate_files.py --override-file overrides.json

  # Filter data
  python aggregate_files.py --filter "Premium>0" --filter "Type==CALL"

  # Keep first occurrence instead of last for duplicates
  python aggregate_files.py --keep-duplicates first
        """
    )

    parser.add_argument(
        "--input-dir", "-i",
        default="..",
        help="Directory containing CSV files (default: parent directory)"
    )
    parser.add_argument(
        "--pattern", "-p",
        default="*_batch*.csv",
        help="Glob pattern to match CSV files (default: *_batch*.csv)"
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output file path (default: aggregated_YYYYMMDD_HHMMSS.csv)"
    )
    parser.add_argument(
        "--override",
        action="append",
        default=[],
        help="Override a field: --override 'column=value' (can be used multiple times)"
    )
    parser.add_argument(
        "--override-file",
        default=None,
        help="JSON file containing field overrides"
    )
    parser.add_argument(
        "--filter",
        action="append",
        default=[],
        help="Filter data: --filter 'column>value' (can be used multiple times)"
    )
    parser.add_argument(
        "--keep-duplicates",
        choices=["first", "last", "none"],
        default="last",
        help="Which duplicate to keep (default: last)"
    )
    parser.add_argument(
        "--no-dedup",
        action="store_true",
        help="Skip duplicate removal"
    )
    parser.add_argument(
        "--include-source",
        action="store_true",
        help="Include source file column in output"
    )
    parser.add_argument(
        "--convert-types",
        action="store_true",
        help="Convert columns to appropriate types (numeric, dates)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without writing output"
    )

    args = parser.parse_args()

    # Find files
    files = find_csv_files(args.input_dir, args.pattern)
    if not files:
        print(f"No files found matching '{args.pattern}' in '{args.input_dir}'")
        sys.exit(1)

    print(f"Found {len(files)} file(s):")
    for f in files:
        print(f"  - {os.path.basename(f)}")

    # Aggregate
    df = aggregate_files(files)
    if df.empty:
        print("No data to aggregate")
        sys.exit(1)

    # Load overrides
    overrides = {}
    if args.override_file:
        overrides.update(load_overrides_from_file(args.override_file))
    for override_str in args.override:
        col, val = parse_override(override_str)
        overrides[col] = val

    # Apply overrides
    df = apply_overrides(df, overrides)

    # Convert types if requested
    if args.convert_types:
        print("\nConverting column types...")
        df = convert_types(df)

    # Parse and apply filters
    filters = {}
    for filter_str in args.filter:
        # Extract column name (everything before the operator)
        for op in [">=", "<=", "!=", "==", ">", "<"]:
            if op in filter_str:
                col = filter_str.split(op)[0]
                filters[col] = filter_str[len(col):]
                break
        else:
            # No operator found, treat as equality
            if "=" in filter_str:
                col, val = filter_str.split("=", 1)
                filters[col] = f"=={val}"

    df = filter_data(df, filters)

    # Remove duplicates
    if not args.no_dedup:
        if args.keep_duplicates == "none":
            # Remove all duplicates
            existing_keys = [k for k in KEY_COLUMNS if k in df.columns]
            if existing_keys:
                df = df.drop_duplicates(subset=existing_keys, keep=False)
        else:
            df = remove_duplicates(df, keep=args.keep_duplicates)

    # Remove source file column if not requested
    if not args.include_source and "_source_file" in df.columns:
        df = df.drop(columns=["_source_file"])

    print(f"\nFinal row count: {len(df)}")

    # Generate output filename
    if args.output is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.output = f"aggregated_{timestamp}.csv"

    # Write output
    if args.dry_run:
        print(f"\nDry run - would write to: {args.output}")
        print(f"Columns: {list(df.columns)}")
        print(f"\nFirst 5 rows:")
        print(df.head())
    else:
        # Save to parent directory of input_dir
        parent_dir = os.path.dirname(args.input_dir.rstrip(os.sep))
        output_path = os.path.join(parent_dir, args.output)
        df.to_csv(output_path, index=False)
        print(f"\nOutput written to: {output_path}")


if __name__ == "__main__":
    # Example usage with field overrides:
    #
    # 1. Override via command line:
    #    python aggregate_files.py --override "ccy_pair=EUR/USD" --override "Lot_size=100"
    #
    # 2. Override via JSON file (create overrides.json):
    #    {
    #        "ccy_pair": "EUR/USD",
    #        "Lot_size": "100",
    #        "Reference": "LSEG_MONTHLY"
    #    }
    #    python aggregate_files.py --override-file overrides.json
    #
    # 3. Combine both methods:
    #    python aggregate_files.py --override-file overrides.json --override "Name=SP500_Options"
    #
    # 4. Full example with filtering and output:
    #    python aggregate_files.py \
    #        --input-dir .. \
    #        --pattern "1EW_*.csv" \
    #        --override "ccy_pair=EUR/USD" \
    #        --override "Lot_size=100" \
    #        --filter "Premium>0" \
    #        --output combined_options.csv
    #

    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\Brent\\all","--pattern", "*_batch*.csv",
        "--output", "downloaded_Brent_20260118.csv",
    ]
    main()   

    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\Gasoil\\all","--pattern", "*_batch*.csv",
        "--output", "downloaded_Gasoil_20260118.csv",
    ]
    main()   

    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\HO\\alloct","--pattern", "*_batch*.csv",
        "--output", "downloaded_HO_20260118_live.csv",
    ]
    main()   
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\HO\\aug-sept","--pattern", "*_batch*.csv",
        "--output", "downloaded_HO_20260118_aug-sept.csv",
    ]
    main()   
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\HO\\rest-2025","--pattern", "*_batch*.csv",
        "--output", "downloaded_HO_20260118_rest-2025.csv",
    ]
    main()   

    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\NaturalGas\\live","--pattern", "*_batch*.csv",
        "--output", "downloaded_NaturalGas_20260118_live.csv",
    ]
    main()  
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\NaturalGas\\expired","--pattern", "*_batch*.csv",
        "--output", "downloaded_NaturalGas_20260118_expired.csv",
    ]
    main()        

    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\WTI\\live","--pattern", "*_batch*.csv",
        "--output", "downloaded_WTI_20260118_live.csv",
    ]
    main()  
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\COMMO\\WTI\\expired","--pattern", "*_batch*.csv",
        "--output", "downloaded_WTI_20260118_expired.csv",
    ]
    main()            

# STOP================================
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FX\\USDAUD\\done","--pattern", "*_batch*.csv",
        "--output", "downloaded_USDAUD_20251001-20260105.csv",
    ]
    main()   

    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FX\\USDCHF\\done","--pattern", "*_batch*.csv",
        "--output", "downloaded_USDCHF_20251001-20260105.csv",
    ]
    main()       

    # sys.argv = ["aggregate_files.py",
    # "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FX\\USDCAD\\done","--pattern", "*_batch*.csv",
    #     "--output", "downloaded_USDCAD_20251001-20260105.csv",
    # ]
    # main()    

    # sys.argv = ["aggregate_files.py",
    # "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FX\\USDEUR\\done","--pattern", "*_batch*.csv",
    #     "--output", "downloaded_USDEUR_20251001-20260105.csv",
    # ]
    # main()    

    # sys.argv = ["aggregate_files.py",
    # "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FX\\USDGBP\\done","--pattern", "*_batch*.csv",
    #     "--output", "downloaded_USDGBP_20251001-20260105.csv",
    # ]
    # main()            


    ## MONDAY #################################################
    # sys.argv = ["aggregate_files.py",
    # "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1_weekly\\monday","--pattern", "*_batch*.csv",
    #     "--output", "downloaded_ty_weekly_monday_20251001-20260105.csv",
    # ]
    #main()
    ## WEDNESDAY #################################################
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1_weekly\\wednesday","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_wednesday_20251001-20260105.csv",
    ]
    main()  
    ## FRIDAY #################################################
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1_weekly\\friday","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_friday_20251001-20260105.csv",
    ]
    main()    




    # ## MONDAY #################################################
    # sys.argv = ["aggregate_files.py",
    #     "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_weekly\\monday",
    #     "--pattern", "*_batch*.csv",
    #     "--output", "downloaded_fv1_weekly_monday_20251001-20260105.csv",
    # ]
    # main()
    # ## WEDNESDAY #################################################
    # sys.argv = ["aggregate_files.py",
    #     "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_weekly\\wednesday",
    #     "--pattern", "*_batch*.csv",
    #     "--output", "downloaded_fv1_weekly_wednesday_20251001-20260105.csv",
    # ]
    # main()
    # ## FRIDAY #################################################
    # sys.argv = ["aggregate_files.py",
    #     "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_weekly\\friday",
    #     "--pattern", "*_batch*.csv",
    #     "--output", "downloaded_fv1_weekly_friday_20251001-20260105.csv",
    # ]
    # main()




    # sys.argv = ["aggregate_files.py",
    #     "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\RX1_weekly\\done_v2",
    #     "--pattern", "*_batch*.csv",
    #     "--output", "downloaded_rx1_weekly_all_20251001-20260102.csv",
    # ]
    # main()

    # sys.argv = ["aggregate_files.py",
    # "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BTP\\done","--pattern", "*_batch*.csv",
    #     "--output", "downloaded_btp_20251001-20260103.csv",
    # ]
    # main()    
    # sys.argv = ["aggregate_files.py",
    #     "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BOBL\\done",
    #     "--pattern", "*_batch*.csv",
    #     "--output", "downloaded_bobl_20251001-20260103.csv",
    # ]
    # main()

    ###########################################################################################################
    # BTP
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BTP\\done\\expired","--pattern", "*_batch*.csv",
        "--output", "downloaded_btp_expired_20251001-20251212.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BTP\\done\\live","--pattern", "*_batch*.csv",
        "--output", "downloaded_btp_live_20251001-20251212.csv",
    ]    
    main()


    ###########################################################################################################
    # TY
    ###########################################################################################################
    
    ## MONDAY #################################################
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1\\done\\expired_mondays","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_monday_expired_20251001-20251212.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1\\done\\live_monday","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_monday_live_20251001-20251212.csv",
    ]     
    main() 

    ## WEDNESDAY #################################################
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1\\done\\expired_wednesdays","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_wednesday_expired_20251001-20251212.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1\\done\\live_wednesday","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_wednesday_live_20251001-20251212.csv",
    ]     
    main() 

    ## FRIDAY #################################################
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1\\done\\expired_fridays","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_friday_expired_20251001-20251212.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
    "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\TY1\\done\\live_friday","--pattern", "*_batch*.csv",
        "--output", "downloaded_ty_weekly_friday_live_20251001-20251212.csv",
    ]
    main()

    ###########################################################################################################
    # BOBL 
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BOBL\\live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_bobl_live_20251001-20251222.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BOBL\\expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_bobl_expired_20251001-20251222.csv",
    ]
    main()    

    ###########################################################################################################
    # BUND
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BUND\\expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_bund_expired_20251001-20251228.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\BUND\\live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_bund_live_20251001-20251228.csv",
    ]
    main()

    ###########################################################################################################
    # FV1 (weekly options - Monday, Wednesday, Friday)
    ###########################################################################################################

    ## MONDAY #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_todo_w\\monday_expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_fv1_weekly_monday_expired_20251001-20251230.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_todo_w\\monday_live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_fv1_weekly_monday_live_20251001-20251230.csv",
    ]
    main()

    ## WEDNESDAY #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_todo_w\\wednesday_expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_fv1_weekly_wednesday_expired_20251001-20251230.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_todo_w\\wednesday_live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_fv1_weekly_wednesday_live_20251001-20251230.csv",
    ]
    main()

    ## FRIDAY #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_todo_w\\friday_expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_fv1_weekly_friday_expired_20251001-20251230.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\FV1_todo_w\\friday_live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_fv1_weekly_friday_live_20251001-20251230.csv",
    ]
    main()

    ###########################################################################################################
    # GILT
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\GILT\\expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_gilt_expired_20251001-20251229.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\GILT\\live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_gilt_live_20251001-20251229.csv",
    ]
    main()

    ###########################################################################################################
    # OAT
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\OAT\\expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_oat_expired_20251001-20251229.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\OAT\\live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_oat_live_20251001-20251229.csv",
    ]
    main()

    ###########################################################################################################
    # RX1 (weekly)
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\RX1_weekly\\expired",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_rx1_weekly_expired_20251001-20251230.csv",
    ]
    main()
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\RX1_weekly\\live",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_rx1_weekly_live_20251001-20251230.csv",
    ]
    main()

    ###########################################################################################################
    # Schatz
    ###########################################################################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\Schatz\\done",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_schatz_20251001-20251229.csv",
    ]
    main()

    ###########################################################################################################
    # UST (multiple tenors)
    ###########################################################################################################

    ## 2Y #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\UST\\done_2y",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_ust_2y_20251001-20251230.csv",
    ]
    main()

    ## 5Y #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\UST\\done_5y",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_ust_5y_20251001-20251230.csv",
    ]
    main()

    ## 10Y #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\UST\\done_10y",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_ust_10y_20251001-20251229.csv",
    ]
    main()

    ## 20Y #################################################
    sys.argv = ["aggregate_files.py",
        "--input-dir", "C:\\Users\\charl\\Dropbox\\MARINER\\DOWNLOAD_FILES\\DOWNLOAD_MONTHLY\\2025-12-Download\\UST\\done_20y",
        "--pattern", "*_batch*.csv",
        "--output", "downloaded_ust_20y_20251001-20251230.csv",
    ]
    main()     